[package]
name = "cheat"
version = "0.1.0"
authors = ["zombie110year <zombie110year@outlook.com>"]
edition = "2018"
description = "manage cheat sheets"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0.2"
clap = "2.33.0"
